AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for LocationApi

Globals:
  Function:
    Timeout: 10

Resources:
  LocationApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/LocationApi/
      Handler: LocationApi::LocationApi.Function::FunctionHandlerAsync
      Runtime: 
      Role: arn:aws:iam::536374685097:role/nihr-dte-dev-eu-west-2-lambdaRole
      MemorySize: 256
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: PassInFromRunConfiguration
          AWS_SECRET_MANAGER_SECRET_NAME: PassInFromRunConfiguration
      Events:
        GetAddressByPostcode:
          Type: Api
          Properties:
            Path: /api/address/{postcode}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LocationApi:
    Description: "API Gateway endpoint URL for Prod stage for LocationApi function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LocationApiFunction:
    Description: "LocationApi Lambda Function ARN"
    Value: !GetAtt LocationApiFunction.Arn
#  LocationApiFunctionIamRole:
#    Description: "Implicit IAM Role created for LocationApi function"
#    Value: !GetAtt LocationApiFunctionRole.Arn
